#!/usr/bin/env sh

# Dmenu for selecting which browser to open.

Browsers='1. B-Brave
2. A-Brave
3. C-Brave
4. R-Brave
qutebrowser
'

Chosen=$(printf '%s' "$Browsers" \
	| dmenu -i -l 20 -p 'Select browser:')
[ -z "$Chosen" ] && exit 1

case $Chosen in
	'1. B-Brave') brave --no-sandbox --profile-directory='Profile 1' "$@";;
	'2. A-Brave') brave --no-sandbox --profile-directory=Default "$@";;
	'3. C-Brave') brave --no-sandbox --profile-directory='Profile 3' "$@";;
	'4. R-Brave') brave --no-sandbox --profile-directory='Profile 2' "$@";;
	qutebrowser) qutebrowser "$@";;
	*) eval "$Chosen" "$@";;
esac
