#!/usr/bin/env sh

# Dmenu for selecting which browser to open.

Browsers='1. B
2. A
3. C
4. R
qutebrowser
'

Chosen=$(printf '%s' "$Browsers" \
	| dmenu -i -l 20 -p 'Select browser:')
[ -z "$Chosen" ] && exit 1

case $Chosen in
	'1. B') brave --no-sandbox --profile-directory='Profile 1' "$@";;
	'2. A') brave --no-sandbox --profile-directory=Default "$@";;
	'3. C') brave --no-sandbox --profile-directory='Profile 3' "$@";;
	'4. R') brave --no-sandbox --profile-directory='Profile 2' "$@";;
	qutebrowser) qutebrowser "$@";;
	*) eval "$Chosen" "$@";;
esac
