#!/usr/bin/env sh

# Link all executable files inside one directory into another.

ScriptName=${0##*/}
Version=1.0.1

HelpMessage="$ScriptName - Version: $Version
Creator: Alexander Chaplin Braz (http://alexchaplinbraz.com)
License: MIT

This script links all the executable files inside one directory into another
directory replacing any existing links. It requires two arguments:

First argument is the directory where the files to be linked are located.
    Use -c for current directory.

Second argument is the directory where to link them.
    Use -b for \$LBIN, if it's set to the local bin folder by the user.

Other options:
    -h | --help         Display this help message and exit.
    -v | --version      Display version and exit.
"

error() {
    printf "ERROR: %s\nTry '%s --help' for more information.\n" \
           "$1" "$ScriptName" 1>&2
    exit 1
}

case $1 in
    -h|--help) printf '%s' "$HelpMessage"; exit 0;;
    -v|--version) printf '%s\n' "$Version"; exit 0;;
esac

if [ -z "$1" ]; then
    error 'a source directory is required.'
elif [ "$1" = '-c' ]; then
    SourceDir=$(pwd)
elif [ -d "$1" ]; then
    SourceDir=$(printf '%s' "$1" | sed 's/\/$//')
else
    error 'invalid source directory.'
fi

if [ -z "$2" ]; then
    error 'a target directory is required.'
elif [ "$2" = '-b' ]; then
    TargetDir=$(printf '%s' "$LBIN" | sed 's/\/$//')
elif [ -d "$2" ]; then
    TargetDir=$(printf '%s' "$2" | sed 's/\/$//')
else
    error 'invalid target directory.'
fi

Files=$(find "$SourceDir" -maxdepth 1 -type f \
             -perm /111 -exec basename {} \; )

for file in $Files; do
    ln -sf "$SourceDir/$file" "$TargetDir/$file"
done
