#!/usr/bin/env sh

# Run this script from the current directory to fix permission on directories
# and files that were transfered from Windows.

# Directories:
find . -type d -exec chmod 775 {} \;

# Files:
find . -type f -exec chmod 644 {} \;
