#!/usr/bin/env sh

# File previewer.

case $1 in
    *.tar*) tar tf "$1";;
    *.zip) unzip -l "$1";;
    *.rar) unrar l "$1";;
    *.7z) 7z l "$1";;
    *.pdf) pdftotext -l 20 -nopgbrk -q "$1" -;;
    *.md) glow -w 80 -s dark "$1";;
    *) highlight -O ansi "$1" || cat "$1";;
esac
