#!/usr/bin/env sh

# Update pacman's mirrorlist, ranked by speed.

ScriptName=${0##*/}
Version=1.0.1
Deps='rate-mirrors date'

Country=ES

HelpMessage="\033[32m$ScriptName\033[0m $Version
Alexander Chaplin Braz <contact@alexchaplinbraz.com>

Update pacman's mirrorlist, ranked by speed.

Must be run as root.

Can change the country in the script itself.
Currently: $Country

\033[33mUSAGE:\033[0m
    $ScriptName
    $ScriptName [FLAG]

\033[33mFLAGS:\033[0m
    \033[32m-h\033[0m, \033[32m--help\033[0m       Print help and exit.
    \033[32m-v\033[0m, \033[32m--version\033[0m    Print version and exit.

\033[33mDEPENDENCIES:\033[0m
    $Deps
"

error() {
    printf "\033[1;31m${2:-ERROR}\033[0m: %s.\nTry '%s --help' for more information.\n" \
        "$1" "$ScriptName" 1>&2
    exit 1
}

info() { printf "\033[1;34m${2:-INFO}\033[0m: %s.\n" "$1" 1>&2; }

case $1 in
    -h|--help) printf '%b' "$HelpMessage"; exit 0 ;;
    -v|--version) printf '%s\n' "$Version"; exit 0 ;;
    '' ) ;;
    *) error "unknown argument '$1'" ;;
esac

for dep in $Deps; do ! command -v $dep 1>/dev/null && MissingDeps="$MissingDeps $dep"; done
[ "$MissingDeps" ] && error "missing dependencies:$MissingDeps"

[ "$(id -u)" -ne 0 ] && error 'must be run as root'

info 'fetching and testing mirrors..'

rate-mirrors --allow-root --entry-country $Country arch > /tmp/mirrorlist_$ScriptName || \
    error 'failed to fetch new mirrors'

CurrentDateTime=$(date +"%Y-%m-%d_%H-%M-%S")

mv -f /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist_backup_$CurrentDateTime && \
    info "a backup can be found at '/etc/pacman.d/mirrorlist_backup_$CurrentDateTime'" || \
    error 'failed to create a backup'

mv -f /tmp/mirrorlist_$ScriptName /etc/pacman.d/mirrorlist && \
    info 'pacman mirrors updated correctly' || \
    error 'failed to move new mirror list'

