#!/usr/bin/env sh

# Dmenu for selecting which browser to open.

Browsers='1. AC
2. ACB
3. CB
4. O'

Chosen=$(printf '%s' "$Browsers" \
	| dmenu -i -l 20 -p 'Select browser:')
[ -z "$Chosen" ] && exit 1

case $Chosen in
	'1. AC') firefox -P AC "$@";;
	'2. ACB') firefox -P ACB "$@";;
	'3. CB') firefox -P CB "$@";;
	'4. O') firefox -P O "$@";;
	*) eval "$Chosen" "$@";;
esac
