#!/usr/bin/env sh

# My own file opener, because xdg-open is annoying to configure.

case "$1" in
	*.md|*.Rmd|*.markdown|*.mdown|*.txt)
		exec $EDITOR "$1"
		;;
	*.html|*.htm)
		exec $BROWSER "$1"
		;;
	*.png|*.jpg|*.jpeg|*.gif)
		exec $IMAGE_VIEWER "$1"
		;;
	*.mp4|*.mov|*.avi|*.wmv|*.flv|*.webm)
		exec $VIDEO_VIEWER "$1"
		;;
	*.mp3|*.wav)
		exec $VIDEO_VIEWER "$1"
		;;
	*.blend)
		exec blmas "$1"
		;;
	*.exe)
		exec dwine "$1"
		;;
# I'd rather have nothing open than have xdg-open decide to open the file
# with something seemingly random.
#	*)
#		export PATH="$DEFAULT_PATH"
#		exec xdg-open "$1"
#		;;
esac

### Need to configure the normal xdg-open so it's somewhat useful.
